#!/bin/bash

# GitHubリポジトリへのpush手順

echo "🚀 GitHub リポジトリへのプッシュ手順"
echo "=================================="
echo ""
echo "このスクリプトは手動で実行してください。"
echo ""
echo "前提条件:"
echo "  - GitHubアカウントがある"
echo "  - GitHub CLI (gh) がインストールされている、または手動でリポジトリを作成"
echo ""
echo "方法1: GitHub CLI を使用（推奨）"
echo "=================================="
echo ""
echo "1. GitHub CLI をインストール（まだの場合）:"
echo "   brew install gh"
echo ""
echo "2. GitHub にログイン:"
echo "   gh auth login"
echo ""
echo "3. リポジトリを作成してプッシュ:"
echo "   gh repo create mysim --public --source=. --remote=origin --push"
echo ""
echo "   または、プライベートリポジトリにする場合:"
echo "   gh repo create mysim --private --source=. --remote=origin --push"
echo ""
echo ""
echo "方法2: 手動でGitHubにリポジトリを作成"
echo "====================================="
echo ""
echo "1. https://github.com/new にアクセス"
echo ""
echo "2. リポジトリ名: mysim"
echo "   説明: Donkey Car Simulator Environment"
echo "   Public または Private を選択"
echo "   「Create repository」をクリック"
echo ""
echo "3. ターミナルで以下を実行:"
echo "   git remote add origin https://github.com/YOUR_USERNAME/mysim.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo ""
echo "プッシュ後に確認すること:"
echo "========================="
echo ""
echo "✅ .gitignore が機能していることを確認"
echo "   → env/ フォルダがプッシュされていないこと"
echo "   → mycar/data/ や mycar/models/ が除外されていること"
echo ""
echo "✅ すべてのドキュメントがアップロードされていること"
echo "   → README.md が表示されること"
echo "   → 全10個の .md ファイルが見えること"
echo ""
echo "✅ リポジトリが正しく表示されること"
echo ""
echo "📝 README.md に以下を追加することをお勧めします:"
echo ""
echo "   - リポジトリのバッジ（GitHub Stars など）"
echo "   - スクリーンショット"
echo "   - デモ動画"
echo "   - ライセンス情報"
echo ""

# 現在の状態を表示
echo ""
echo "📊 現在の Git 状態:"
echo "==================="
git log --oneline -5
echo ""
echo "コミット数: $(git rev-list --count HEAD)"
echo "ブランチ: $(git branch --show-current)"
echo ""
